version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: fastapi-backend
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@postgres/mydatabase
    ports:
      - "80:80"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
    container_name: vue-frontend
    ports:
      - "8080:8080"

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
